apiVersion: apps/v1
kind: Deployment
metadata:
  name: superpai-docs
  namespace: superpai-docs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: superpai-docs
  template:
    metadata:
      labels:
        app: superpai-docs
    spec:
      imagePullSecrets:
        - name: superpai-docs-registry   # synced by InfisicalSecret CR infisical-secret.yaml
      containers:
        - name: superpai-docs
          image: registry.anshinhealth.net/engineering/superpai/docs:dev-latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
